# DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!
target 'MyApp' do
	project 'MyApp.xcodeproj'
	pod 'TrustKit', '~> 1.6'
end
